### ISSUE TITLE
http模块调用 https接口，提示ssl错误

### ISSUE THREAD

**Issue by just3019** [ssssssss-team/magic-api#32]
调用https接口，提示ssl错误，这个需要在哪里处理，或者skip掉ssl验证。

```
接口/magic/getAlarmList请求出错org.ssssssss.script.exception.MagicScriptException: I/O error on GET request for "https://xxx/openapi/v1.0/info": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at Row:11~11,Col:9~12



var obj=http.header("apiKey","551dff0bd8a4ddce4292b38effc81b8b").param(map).connect("https://xxx/openapi/v1.0/info").get();

        ^^^^                                                                                                                                   

at org.ssssssss.script.MagicScriptError.error(MagicScriptError.java:71)

at org.ssssssss.script.MagicScriptError.transfer(MagicScriptError.java:114)

at org.ssssssss.script.MagicScript.execute(MagicScript.java:97)

at org.ssssssss.script.MagicScript.eval(MagicScript.java:153)

at org.ssssssss.magicapi.script.ScriptManager.executeScript(ScriptManager.java:66)

at org.ssssssss.magicapi.controller.RequestHandler.invokeRequest(RequestHandler.java:264)

at org.ssssssss.magicapi.controller.RequestHandler.invoke(RequestHandler.java:124)

at jdk.internal.reflect.GeneratedMethodAccessor288.invoke(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197)

at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141)

at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106)

at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)

at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)

at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064)

at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)

at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)

at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)

at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)

at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)

at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)

at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)

at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)

at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)

at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)

at org.ssssssss.magicapi.config.MagicCorsFilter.doFilter(MagicCorsFilter.java:42)

at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190)

at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163)

at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)

at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)

at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)

at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)

at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)

at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)

at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)

at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)

at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)

at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)

at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723)

at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)

at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)

at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785)

at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711)

at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602)

at org.ssssssss.magicapi.modules.HttpModule.execute(HttpModule.java:173)

at org.ssssssss.magicapi.modules.HttpModule.get(HttpModule.java:139)

at jdk.internal.reflect.GeneratedMethodAccessor292.invoke(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

at java.base/java.lang.reflect.Method.invoke(Method.java:566)

at org.ssssssss.script.reflection.MethodInvoker.invoke(MethodInvoker.java:20)

at org.ssssssss.script.reflection.JavaInvoker.invoke0(JavaInvoker.java:83)

at org.ssssssss.script.runtime.handle.FunctionCallHandle.invoke_method(FunctionCallHandle.java:138)

at MagicScript_65.execute(MagicScript_65.ms:11)

at org.ssssssss.script.MagicScript.execute(MagicScript.java:93)

... 56 more
```

**Comment by javamxd** [comment]
这个模块是封装的`RestTemplate`，你自己定义一个`RestTemplate`的`Bean`就可以配置这些东西了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ssssssss-team/magic-api"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 上午10:07
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[ssssssss-team/magic-api] http模块调用 https接口，提示ssl错误 (Issue #32)





 
调用https接口，提示ssl错误，这个需要在哪里处理，或者skip掉ssl验证。
 接口/magic/getAlarmList请求出错org.ssssssss.script.exception.MagicScriptException: I/O error on GET request for "https://xxx/openapi/v1.0/info": PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target; nested exception is javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at Row:11~11,Col:9~12 var obj=http.header("apiKey","551dff0bd8a4ddce4292b38effc81b8b").param(map).connect("https://xxx/openapi/v1.0/info").get();         ^^^^                                                                                                                                    at org.ssssssss.script.MagicScriptError.error(MagicScriptError.java:71) at org.ssssssss.script.MagicScriptError.transfer(MagicScriptError.java:114) at org.ssssssss.script.MagicScript.execute(MagicScript.java:97) at org.ssssssss.script.MagicScript.eval(MagicScript.java:153) at org.ssssssss.magicapi.script.ScriptManager.executeScript(ScriptManager.java:66) at org.ssssssss.magicapi.controller.RequestHandler.invokeRequest(RequestHandler.java:264) at org.ssssssss.magicapi.controller.RequestHandler.invoke(RequestHandler.java:124) at jdk.internal.reflect.GeneratedMethodAccessor288.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:197) at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:141) at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1064) at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963) at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) at javax.servlet.http.HttpServlet.service(HttpServlet.java:655) at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) at javax.servlet.http.HttpServlet.service(HttpServlet.java:764) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:228) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) at org.ssssssss.magicapi.config.MagicCorsFilter.doFilter(MagicCorsFilter.java:42) at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:190) at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:163) at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97) at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542) at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143) at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78) at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357) at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382) at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:785) at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:711) at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:602) at org.ssssssss.magicapi.modules.HttpModule.execute(HttpModule.java:173) at org.ssssssss.magicapi.modules.HttpModule.get(HttpModule.java:139) at jdk.internal.reflect.GeneratedMethodAccessor292.invoke(Unknown Source) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.base/java.lang.reflect.Method.invoke(Method.java:566) at org.ssssssss.script.reflection.MethodInvoker.invoke(MethodInvoker.java:20) at org.ssssssss.script.reflection.JavaInvoker.invoke0(JavaInvoker.java:83) at org.ssssssss.script.runtime.handle.FunctionCallHandle.invoke_method(FunctionCallHandle.java:138) at MagicScript_65.execute(MagicScript_65.ms:11) at org.ssssssss.script.MagicScript.execute(MagicScript.java:93) ... 56 more  
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by javamxd** [comment]
这个模块是封装的`RestTemplate`，你自己定义一个`RestTemplate`的`Bean`就可以配置这些东西了

**Comment by just3019** [comment]
我自己定义了一个resttemplate，还是报错。我翻了一下MagicApiAutoConfigration 这个类，里面HttpModule的初始化是入参了一个createRestTemplate方法，我直接定义一个restTemplate的bean应该没有作用吧。

![16365117622013332126018_46157743977_DINGTALK_IM_2511134365 JPG](https://user-images.githubusercontent.com/5235712/141039332-7dc35415-c604-4398-b0fc-c06ccbcb52bd.JPG)

![3332126018_46158218095_DINGTALK_IM_1900502116 JPG](https://user-images.githubusercontent.com/5235712/141039684-5e9dc924-9ef8-4ac0-ac06-670b84a09767.JPG)

**Comment by javamxd** [comment]
好像确实。。。那就改成自己定义一个`HttpModule`

**Comment by just3019** [comment]
thanks，可以了。自己定义了一个httpModule

![3332126018_46158639869_DINGTALK_IM_1172750506 JPG](https://user-images.githubusercontent.com/5235712/141039920-bc62200b-6539-4365-8897-a4b06b0758d1.JPG)
